[package]
name = "kvm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "^0.2.0"
errno = "^0.2.8"
libkvm = { path = "./libkvm" }

[dev-dependencies]

[workspace]
members = ["libkvm"]
